spring.application.name=sports-storage-service
server.port=8084

# Nacos 服务发现配置
cloud.nacos.discovery.server-addr=localhost:8848

# MySQL 配置
spring.datasource.url=jdbc:mysql://localhost:3306/sports_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# Redis 配置
spring.redis.host=localhost
spring.redis.port=6379

# RocketMQ 配置
rocketmq.consumer.group=my-consumer-group
rocketmq.name-server=localhost:9876