spring.application.name=sports-api-gateway
server.port=8080

# Nacos 服务发现配置
cloud.nacos.discovery.server-addr=localhost:8848

# Spring Cloud Gateway 路由配置
spring.cloud.gateway.routes[0].id=sports-data-crawler
spring.cloud.gateway.routes[0].uri=lb://sports-data-crawler
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/data/**

spring.cloud.gateway.routes[1].id=sports-push-service
spring.cloud.gateway.routes[1].uri=lb://sports-push-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/push/**

spring.cloud.gateway.routes[2].id=sports-storage-service
spring.cloud.gateway.routes[2].uri=lb://sports-storage-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/storage/**

spring.cloud.gateway.routes[3].id=sports-statistic-service
spring.cloud.gateway.routes[3].uri=lb://sports-statistic-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/stat/**